Peekpa/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.peekpauser.urls')), #添加的PeekpaUser的url路径
    path('cms/', include('apps.cms.urls')),
    path('', include('apps.basefunction.urls')),
    path('', include('apps.poster.urls')),
    path('', include('apps.datacenter.urls')),
    path('api-token/', obtain_auth_token)
]

apps/cms/urls.py
from django.urls import path
from . import views
from .category_view import CategoryView, CategoryEditView, CategoryDeleteView
from .tag_view import TagView, TagEditView, TagDeleteView
from .post_view import PostView, PostEditView, PostDeleteView
from .exchangelink_view import ExchangeLinkView, ExchangeLinkEditView, ExchangeLinkDeleteView
from .navitem_view import NavItemView, NavItemEditView, NavItemDeleteView
from .code_view import CodeView, CodeEditView, CodeDeleteView
from .user_view import UserView, UserDeleteView
from .feature_view import FeatureView, FeatureEditView, FeatureDeleteView


app_name = "cms"

urlpatterns = [
    path("", views.cms_login, name="index"),
    path("dashboard/", views.cms_dashboard, name="dashboard"),
    path("login/", views.cms_login, name="login"),
    path("dashboard/category/manage", views.category_manage_view, name="category_manage_view"),
    path("dashboard/category/publish", views.category_publish_view, name="category_publish_view"),
    path("dashboard/category/add", CategoryView.as_view(), name="category_add"),
    path("dashboard/category/edit", CategoryEditView.as_view(), name="category_edit"),
    path("dashboard/category/delete", CategoryDeleteView.as_view(), name="category_delete"),

    path("dashboard/tag/manage", views.tag_manage_view, name="tag_manage_view"),
    path("dashboard/tag/publish", views.tag_publish_view, name="tag_publish_view"),
    path("dashboard/tag/add", TagView.as_view(), name="tag_add"),
    path("dashboard/tag/edit", TagEditView.as_view(), name="tag_edit"),
    path("dashboard/tag/delete", TagDeleteView.as_view(), name="tag_delete"),

    path("dashboard/post/manage", views.post_manage_view, name="post_manage_view"),
    path("dashboard/post/publish", views.post_publish_view, name="post_publish_view"),
    path("dashboard/post/add", PostView.as_view(), name="post_add"),
    path("dashboard/post/edit", PostEditView.as_view(), name="post_edit"),
    path("dashboard/post/delete", PostDeleteView.as_view(), name="post_delete"),

    path("dashboard/exchangelink/manage", views.exchangelink_manage_view, name="exchangelink_manage_view"),
    path("dashboard/exchangelink/publish", views.exchangelink_publish_view, name="exchangelink_publish_view"),
    path("dashboard/exchangelink/add", ExchangeLinkView.as_view(), name="exchangelink_add"),
    path("dashboard/exchangelink/edit", ExchangeLinkEditView.as_view(), name="exchangelink_edit"),
    path("dashboard/exchangelink/delete", ExchangeLinkDeleteView.as_view(), name="exchangelink_delete"),

    path("dashboard/navitem/manage", views.navitem_manage_view, name="navitem_manage_view"),
    path("dashboard/navitem/publish", views.navitem_publish_view, name="navitem_publish_view"),
    path("dashboard/navitem/add", NavItemView.as_view(), name="navitem_add"),
    path("dashboard/navitem/edit", NavItemEditView.as_view(), name="navitem_edit"),
    path("dashboard/navitem/delete", NavItemDeleteView.as_view(), name="navitem_delete"),

    path("dashboard/monitor/userip", views.monitor_userip_view, name="monitor_userip_view"),
    path("dashboard/monitor/postview", views.monitor_postview_view, name="monitor_postview_view"),

    path("dashboard/code/manage", views.code_manage_view, name="code_manage_view"),
    path("dashboard/code/publish", views.code_publish_view, name="code_publish_view"),
    path("dashboard/code/add", CodeView.as_view(), name="code_add"),
    path("dashboard/code/edit", CodeEditView.as_view(), name="code_edit"),
    path("dashboard/code/delete", CodeDeleteView.as_view(), name="code_delete"),

    path("dashboard/user/manage", views.user_manage_view, name="user_manage_view"),
    path("dashboard/user/publish", views.user_publish_view, name="user_publish_view"),
    path("dashboard/user/add", UserView.as_view(), name="user_add"),
    path("dashboard/user/delete", UserDeleteView.as_view(), name="user_delete"),

    path("dashboard/inputcode/manage", views.data_center_inputcode_manage_view, name="data_center_inputcode_manage_view"),
    path("dashboard/inputcode/modify", views.data_center_inputcode_modify_view, name="data_center_inputcode_modify"),

    path("dashboard/feature/manage", views.feature_manage_view, name="feature_manage_view"),
    path("dashboard/feature/publish", views.feature_publish_view, name="feature_publish_view"),
    path("dashboard/feature/add", FeatureView.as_view(), name="feature_add"),
    path("dashboard/feature/edit", FeatureEditView.as_view(), name="feature_edit"),
    path("dashboard/feature/delete", FeatureDeleteView.as_view(), name="feature_delete"),

    path("dashboard/cache/manage", views.cache_manage_view, name="cache_manage_view"),
    path("dashboard/cache/delete", views.cache_delete_item_view, name="cache_item_clear"),
    path("dashboard/cache/deleteall", views.cache_clear_view, name="cache_clear"),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/views.py
import datetime

from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.shortcuts import redirect, reverse

from apps.base.redis_cache import get_cache_keys_object
from apps.poster.models import Category, Tag, Post
from apps.basefunction.models import VisitNumber, DayNumber, UserIP
from apps.exchangelink.models import ExchangeLink
from apps.basefunction.models import NavbarItem, FeaturePost
from apps.peekpauser.models import User
from apps.datacenter.models import Code, InputCode
from django.core.paginator import Paginator
from django.core.cache import cache
from apps.peekpauser.decorators import peekpa_login_required, peekpa_login_superuser
from apps.basefunction.global_peekpa import init_peekpa, get_peekpa_item
from django.conf import settings

# Create your views here.


def cms_login(request):
    return render(request, 'cms/login.html')


@peekpa_login_required
def cms_dashboard(request):
    init_peekpa()
    context = {
        'peekpa_config_code_list': get_peekpa_item("CODE"),
        'peekpa_config_navitem_list': get_peekpa_item("NAVITEM"),
        'list_data_show_page': NavbarItem.SHOW_PAGE_ITEMS,
        'peekpa_version': settings.PEEKPA_VERSION
    }
    context.update(get_dashboard_top_data())
    context.update(get_dashboard_visitor_chart())
    context.update(get_dashboard_visitor_ip_table(10))
    context.update(get_dashboard_post_view_table(10))
    return render(request, 'cms/home/home.html', context=context)


@peekpa_login_required
def category_manage_view(request):
    context = {
        "list_data": Category.objects.all()
    }
    return render(request, 'cms/category/manage.html', context=context)


@peekpa_login_required
def category_publish_view(request):
    return render(request, 'cms/category/publish.html')


@peekpa_login_required
def tag_manage_view(request):
    context = {
        "list_data": Tag.objects.all()
    }
    return render(request, 'cms/tag/manage.html', context=context)


@peekpa_login_required
def tag_publish_view(request):
    return render(request, 'cms/tag/publish.html')


@peekpa_login_required
def post_manage_view(request):
    page = int(request.GET.get('p', 1))
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.ONE_PAGE_NEWS_COUNT)
    page_obj = paginator.page(page)
    context = {
        "list_data": page_obj.object_list,
        'list_data_status': Post.STATUS_ITEMS,
        'url_tag_info': ['post', 'post.manage']
    }
    context_data = get_pagination_data(paginator, page_obj)
    context.update(context_data)
    return render(request, 'cms/post/manage.html', context=context)


@peekpa_login_required
def post_publish_view(request):
    context = {
        'list_data_category': Category.objects.all(),
        'list_data_tag': Tag.objects.all(),
        'list_data_user': User.objects.all(),
        'list_data_status': Post.STATUS_ITEMS,
        'url_tag_info': ['post', 'post.publish']
    }
    return render(request, 'cms/post/publish.html', context=context)


def get_pagination_data(paginator, page_obj, around_count=2):
    current_page = page_obj.number
    num_pages = paginator.num_pages

    left_has_more = False
    right_has_more = False

    if current_page <= around_count + settings.ONE_PAGE_NEWS_COUNT:
        left_pages = range(1, current_page)
    else:
        left_has_more = True
        left_pages = range(current_page - around_count, current_page)

    if current_page >= num_pages - around_count - 1:
        right_pages = range(current_page + 1, num_pages + 1)
    else:
        right_has_more = True
        right_pages = range(current_page + 1, current_page + around_count + 1)

    return {
        # left_pages：代表的是当前这页的左边的页的页码
        'left_pages': left_pages,
        # right_pages：代表的是当前这页的右边的页的页码
        'right_pages': right_pages,
        'current_page': current_page,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'num_pages': num_pages
    }


@peekpa_login_required
def exchangelink_manage_view(request):
    context = {
        "list_data": ExchangeLink.objects.all(),
        'list_data_status': ExchangeLink.STATUS_ITEMS
    }
    return render(request, 'cms/exchangelink/manage.html', context=context)


@peekpa_login_required
def exchangelink_publish_view(request):
    context = {
        'list_data_status': ExchangeLink.STATUS_ITEMS
    }
    return render(request, 'cms/exchangelink/publish.html', context=context)


@peekpa_login_required
def navitem_manage_view(request):
    context = {
        "list_data": NavbarItem.objects.all(),
        'list_data_status': NavbarItem.STATUS_ITEMS,
        'list_data_show_page': NavbarItem.SHOW_PAGE_ITEMS,
    }
    return render(request, 'cms/navitem/manage.html', context=context)


@peekpa_login_required
def feature_manage_view(request):
    context = {
        "list_data": FeaturePost.objects.all(),
        'list_data_status': FeaturePost.STATUS_ITEMS,
    }
    return render(request, 'cms/feature/manage.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
def code_manage_view(request):
    context = {
        "list_data": Code.objects.all(),
        'list_data_status': Code.STATUS_ITEMS,
    }
    return render(request, 'cms/code/manage.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
def user_manage_view(request):
    context = {
        "list_data": User.objects.all(),
    }
    return render(request, 'cms/user/manage.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
def data_center_inputcode_manage_view(request):
    context = {
        "item_data": InputCode.objects.get_or_create(id=1)[0],
    }
    return render(request, 'cms/datacenter/input_code.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
@require_POST
def data_center_inputcode_modify_view(request):
    name = request.POST.get('name')
    InputCode.objects.filter(id=1).update(name=name)
    return redirect(reverse('cms:data_center_inputcode_manage_view'))


@peekpa_login_required
def monitor_userip_view(request):
    page = int(request.GET.get('p', 1))
    posts = UserIP.objects.all().order_by('-create_time')
    paginator = Paginator(posts, settings.ONE_PAGE_NEWS_COUNT)
    page_obj = paginator.page(page)
    day_count = DayNumber.objects.filter(day=timezone.now().date())
    ip_count_num = day_count[0].count if day_count else 0

    context = {
        "list_data": page_obj.object_list,
        "day_time": timezone.now().date(),
        "ip_count_num": ip_count_num
    }
    context_data = get_pagination_data(paginator, page_obj)
    context.update(context_data)
    return render(request, 'cms/monitor/userip_manage.html', context=context)


@peekpa_login_required
def monitor_postview_view(request):
    page = int(request.GET.get('p', 1))
    posts = get_dashboard_post_view_table(-1)['post_view_table_list']
    paginator = Paginator(posts, settings.ONE_PAGE_NEWS_COUNT)
    page_obj = paginator.page(page)
    context = {
        "list_data": page_obj.object_list,
    }
    context_data = get_pagination_data(paginator, page_obj)
    context.update(context_data)
    return render(request, 'cms/monitor/post_view_manage.html', context=context)


@peekpa_login_required
def navitem_publish_view(request):
    context = {
        'list_data_status': NavbarItem.STATUS_ITEMS,
        'list_data_show_page': NavbarItem.SHOW_PAGE_ITEMS,
    }
    return render(request, 'cms/navitem/publish.html', context=context)


@peekpa_login_required
def feature_publish_view(request):
    context = {
        'list_data_status': FeaturePost.STATUS_ITEMS,
    }
    return render(request, 'cms/feature/publish.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
def code_publish_view(request):
    context = {
        'list_data_status': Code.STATUS_ITEMS,
    }
    return render(request, 'cms/code/publish.html', context=context)


@peekpa_login_required
@peekpa_login_superuser
def user_publish_view(request):
    context = {

    }
    return render(request, 'cms/user/publish.html', context=context)


def get_dashboard_top_data():
    post_num = Post.objects.all().count()
    day_visit_ip_set = set()
    day_visit_ip_list = UserIP.objects.filter(day=timezone.now().date())
    if day_visit_ip_list:
        for user_ip_item in day_visit_ip_list:
            if user_ip_item.ip_address not in day_visit_ip_set:
                day_visit_ip_set.add(user_ip_item.ip_address)
    day_visit_ip_num = len(day_visit_ip_set)
    day_visit_num = DayNumber.objects.filter(day=timezone.now().date())[0].count
    total_visit_num = VisitNumber.objects.filter(id=1)[0].count
    context = {
        "post_num": post_num,
        "day_visit_ip_num": day_visit_ip_num,
        "day_visit_num": day_visit_num,
        "total_visit_num": total_visit_num
    }
    return context


def get_dashboard_visitor_ip_table(max_num):
    visitor_data = UserIP.objects.filter(day=timezone.now().date())
    if len(visitor_data):
        visitor_data = visitor_data[:max_num]
    context = {
        'visitor_data_list': visitor_data,
    }
    return context


def get_dashboard_visitor_chart():
    days_list = []
    visit_list = []
    max_num = 0
    week_total_num = 0
    for index in range(6, -1, -1):
        day, format_date = get_before_date(index)
        days_list.append(int(day))
        day_visit_num = 0
        daynumber_item = DayNumber.objects.filter(day=format_date)
        if daynumber_item:
            day_visit_num = daynumber_item[0].count
        visit_list.append(day_visit_num)
        week_total_num += day_visit_num
        max_num = day_visit_num if day_visit_num > max_num else max_num
    context = {
        'visit_week_total_number': day_visit_num,
        'date_time_list': days_list,
        'week_data_list': visit_list,
        'suggested_max': max_num
    }
    return context


def get_before_date(day):

front/templates/cms/code/manage.html
{% extends 'cms/base/dashboard_base.html' %}

{% block head %}
    <script src="{% static 'js/code_manage.min.js' %}"></script>
{% endblock %}

{% block title %}
    Code Management
{% endblock %}

{% block main %}
    <section class="content">
        <div class="container-fluid pt-4">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row p-2 d-flex justify-content-between">
                                <p class="h3">Codes</p>
                                <div class="float-right">
                                    <a class="btn btn-primary text-right" href="{% url 'cms:code_publish_view' %}"><i class="mr-2 fas fa-plus"></i>Add</a>
                                </div>
                            </div>
                            <table class="table table-bordered table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th style="width: 10%;">code</th>
                                        <th>session_uid</th>
                                        <th>session_name</th>
                                        <th>visit_num</th>
                                        <th>status</th>
                                        <th class="w-25">actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in list_data %}
                                        <tr>
                                            <td>{{ item.code }}</td>
                                            <td>{{ item.session_uid }}</td>
                                            <td>{{ item.session_name }}</td>
                                            <td>{{ item.visit_num }}</td>
                                            <td>
                                                {% for list_item in list_data_status %}
                                                    {% if item.status == list_item.0 %}
                                                        {{ list_item.1 }}
                                                    {% endif %}
                                                {% endfor %}
                                            </td>
                                            <td>
                                                <a href="{% url 'cms:code_edit' %}?code_id={{ item.uid }}" class="btn btn-info btn-xs">Modify</a>
                                                <button class="btn btn-danger btn-xs delete-btn" data-code-id="{{ item.uid}}">
                                                    Delete
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



{% endblock %}

front/templates/cms/code/publish.html
{% extends 'cms/base/dashboard_base.html' %}

{% block title %}
    {% if item_data %}
        Code Edit
    {% else %}
        Code Publish
    {% endif %}
{% endblock %}

{% block main %}
    <section class="content">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center pt-4">
                <div class="col-sm-10">
                    <div class="card card-primary">
                        <div class="card-header">
                            {% if item_data %}
                                <h3 class="card-title">Code Edit</h3>
                            {% else %}
                                <h3 class="card-title">Code Publish</h3>
                            {% endif %}
                        </div>
                        <!-- form start -->
                        <form class="form-horizontal" action="{% url 'cms:code_add' %}" method="post">
                            {% csrf_token %}
                            {% if item_data %}
                                <input type="text" class="form-control" id="pk" name="pk" value="{{ item_data.uid }}" hidden>
                            {% endif %}
                            <div class="card-body">
                                <div class="form-group row ">
                                    <label for="code" class="col-form-label col-sm-2 text-center">Code</label>
                                    <div class="col-sm-10">
                                        {% if item_data %}
                                            <input type="text" class="form-control" id="code" name="code" value="{{ item_data.code }}">
                                        {% else %}
                                            <input type="text" class="form-control" id="code" name="code">
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="form-group row ">
                                    <label for="session_name" class="col-form-label col-sm-2 text-center">Session Name</label>
                                    <div class="col-sm-10">
                                        {% if item_data %}
                                            <input type="text" class="form-control" id="session_name" name="session_name" value="{{ item_data.session_name }}">
                                        {% else %}
                                            <input type="text" class="form-control" id="session_name" name="session_name">
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="status" class="col-form-label col-sm-2 text-center">Status</label>
                                    <div class="col-sm-10">
                                        <select name="status" id="status" class="custom-select ">
                                            {% if item_data %}
                                                {% for item in list_data_status %}
                                                    <option value="{{ item.0 }}" {% if item.0 == item_data.status %} selected {% endif %}>{{ item.1 }}</option>
                                                {% endfor %}
                                            {% else %}
                                                {% for item in list_data_status %}
                                                    <option value="{{ item.0 }}">{{ item.1 }}</option>
                                                {% endfor %}
                                            {% endif %}
                                        </select>
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                {% if item_data %}
                                    <button type="submit" class="btn btn-info" name="modify">Submit</button>
                                    <button type="submit" class="btn btn-danger float-right" name="cancel">Cancel</button>
                                {% else %}
                                    <button type="submit" class="btn btn-info" name="submit">Submit</button>
                                    <button type="submit" class="btn btn-danger float-right" name="back">Back</button>
                                {% endif %}
                            </div>
                            <!-- /.card-footer -->
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}